package com.example.smsguard.ui.theme

import androidx.compose.ui.graphics.Color

val GreenPrimary = Color(0xFF006D3D)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFF9BF6BC)
val GreenOnPrimaryContainer = Color(0xFF00210F)
val GreenSecondary = Color(0xFF4D6352)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFCFE8D2)
val GreenOnSecondaryContainer = Color(0xFF092012)
val GreenTertiary = Color(0xFF3B6470)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFBEE9F7)
val GreenOnTertiaryContainer = Color(0xFF001F27)
val GreenBackground = Color(0xFFFBFDF7)
val GreenOnBackground = Color(0xFF191C19)
val GreenSurface = Color(0xFFFBFDF7)
val GreenOnSurface = Color(0xFF191C19)
val GreenSurfaceVariant = Color(0xFFDCE5DC)
val GreenOnSurfaceVariant = Color(0xFF404943)
val GreenOutline = Color(0xFF707973)
val GreenError = Color(0xFFBA1A1A)
val GreenOnError = Color(0xFFFFFFFF)

val GreenPrimaryDark = Color(0xFF7FD9A2)
val GreenOnPrimaryDark = Color(0xFF003921)
val GreenPrimaryContainerDark = Color(0xFF00522F)
val GreenOnPrimaryContainerDark = Color(0xFF9BF6BC)
val GreenSecondaryDark = Color(0xFFB4CCB8)
val GreenOnSecondaryDark = Color(0xFF203527)
val GreenSecondaryContainerDark = Color(0xFF364B3D)
val GreenOnSecondaryContainerDark = Color(0xFFCFE8D2)
val GreenTertiaryDark = Color(0xFFA2CDDA)
val GreenOnTertiaryDark = Color(0xFF00363F)
val GreenTertiaryContainerDark = Color(0xFF224C57)
val GreenOnTertiaryContainerDark = Color(0xFFBEE9F7)
val GreenBackgroundDark = Color(0xFF111412)
val GreenOnBackgroundDark = Color(0xFFDEE4DD)
val GreenSurfaceDark = Color(0xFF111412)
val GreenOnSurfaceDark = Color(0xFFDEE4DD)
val GreenSurfaceVariantDark = Color(0xFF404943)
val GreenOnSurfaceVariantDark = Color(0xFFC0C9C1)
val GreenOutlineDark = Color(0xFF8A938C)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)